# Linear Regression
* supervised algorithm
* finding linear relationship between independent variable and dependent variable
* finds relationship between two or more continuous variables

<img src="https://static.javatpoint.com/tutorial/machine-learning/images/linear-regression-in-machine-learning.png" alt="Linear Regression" />

## Type linear regression

`* Single Linear Regression`

y = m x + c

`* Multiple Linear Regression` 

y = m1 x1 + m2 x2 + ....+ c

note :

y = dependent variables

x = independent variables

## Simple Linear Regression

### Import packages and classes

In [6]:
#import library
import numpy as np
from sklearn.linear_model import LinearRegression

In [8]:
x = np.array([25,35,45,55,65,76])       # independent
y = np.array([5,20,14,32,22,38])        # dependent 

print(x)
print(y)

[25 35 45 55 65 76]
[ 5 20 14 32 22 38]


In [10]:
# reshape x because this array require to be two dimensional
x = x.reshape((-1,1))
print(x)

[[25]
 [35]
 [45]
 [55]
 [65]
 [76]]


### Create model and fit it

In [11]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [12]:
# check model fitted and interpret it
r_sq_score = model.score(x,y)
print('coefficient determination :',r_sq_score)

coefficient determination : 0.7196741132389521


71% coefficient

In [13]:
# intercept
print('intercept :',model.intercept_)

intercept : -4.942341508560851


In [14]:
# slope
print('slope :',model.coef_)

slope : [0.53373438]


### Model Prediction

In [15]:
y_pred = model.predict(x)

print('predict response :',y_pred)

predict response : [ 8.40101805 13.73836187 19.07570569 24.41304951 29.75039334 35.62147154]


In [16]:
#actual values vs prediction values
print(y)
print(y_pred)

[ 5 20 14 32 22 38]
[ 8.40101805 13.73836187 19.07570569 24.41304951 29.75039334 35.62147154]


## Multiple Linear Regression

### Import packages and classes

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = [[10,21],[5,18],[15,24],[25,56],[35,11],[55,15],[55,34],[90,35]]    # multi values
y = [4,14,15,20,14,32,22,38]    # single values

print(x)
print(y)

[[10, 21], [5, 18], [15, 24], [25, 56], [35, 11], [55, 15], [55, 34], [90, 35]]
[4, 14, 15, 20, 14, 32, 22, 38]


in multiple linear regression, x is two dimensional and y is one dimensional array

In [5]:
x,y = np.array(x), np.array(y)
print(x)
print(y)

[[10 21]
 [ 5 18]
 [15 24]
 [25 56]
 [35 11]
 [55 15]
 [55 34]
 [90 35]]
[ 4 14 15 20 14 32 22 38]


### Create Model and fit it

In [12]:
model = LinearRegression()

In [14]:
model.fit(x,y)

LinearRegression()

### Get results

In [15]:
r_square = model.score(x,y)
print('coeffficent determination :',r_square)

coeffficent determination : 0.7986296843961266


79% accuracy 

In [16]:
print('intercept:',model.intercept_)

intercept: 6.172850554140558


In [17]:
print('slope:',model.coef_)

slope: [0.32809312 0.06761772]


### Predict responses

In [20]:
y_pred = model.predict(x)
print('Predicted response :',y_pred,sep='\n')

Predicted response :
[10.87375382  9.03043508 12.71707256 18.16177074 18.39990453 25.23223772
 26.51697439 38.06785117]


In [21]:
# actual values vs predict values
print('Actual values :',y)
print('Predict values :',y_pred) # 79% accuracy

Actual values : [ 4 14 15 20 14 32 22 38]
Predict values : [10.87375382  9.03043508 12.71707256 18.16177074 18.39990453 25.23223772
 26.51697439 38.06785117]
